"""
 Functions to read in the projected frequencies generated by ProjRot
"""


def rpht_output(file_name):
    """ Read the projected frequencies
    """

    # Read the file and read in the non-zero frequencies
    freqs = []
    with open(file_name, 'r') as freq_file:
        for line in freq_file:
            if line.strip() != '':
                freqs.append(float(line.strip()))

    # Build lists for the real and imaginary frequencies
    real_freqs = []
    imag_freqs = []
    for freq in freqs:
        # Ignore zeros and grab the negative vals from projrot out_str
        if freq != 0.0:
            if freq > 0.0:
                real_freqs.append(freq)
            else:
                imag_freqs.append(-1.0*freq)
    
    # Sort imaginary freqeuncies in descending order
    imag_freqs.sort(reverse=True)

    return real_freqs, imag_freqs
