"""
 Functions to read in the projected frequencies generated by ProjRot
"""


def rpht_output(file_name):
    """ Read the projected frequencies
    """

    # Read the file and read in the non-zero frequencies
    freqs = []
    with open(file_name, 'r') as freq_file:
        for line in freq_file:
            if line.strip() != '':
                freqs.append(float(line.strip()))

    # Build lists for the real and imaginary frequencies
    real_freqs = []
    imag_freqs = []
    for i, val in enumerate(freqs):
        # Ignore zeros
        if val != 0.0:
            # Always include the first element (so logic later works)
            if i == 0:
                real_freqs.append(val)
            else:
                # If current val higher than previous, it is an imag. number
                if freqs[i] < freqs[i-1]:
                    real_freqs.append(val)
                else:
                    imag_freqs.append(val)

    return real_freqs, imag_freqs
